name: CI/CD

run-name: Start ${{ github.workflow }} by ${{ github.actor }} 🚀

env:
  APP_NAME: distant-work-calendar-service
  APP_PORT: 7466
  USE_TAG: latest

on: workflow_dispatch

jobs:
  init-environments:
    name: Init Environments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Find commit short sha
        id: short_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    outputs:
      sha_short: ${{ steps.short_sha.outputs.sha_short }}


  build-and-push-iamge:
    name: Build&Push
    needs: init-environments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY_ADDRESS }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6.1.0
        with:
          file: docker/Dockerfile
          context: .
          tags: ${{ secrets.CONTAINER_REGISTRY_ADDRESS }}/${{ env.APP_NAME }}:${{ needs.init-environments.outputs.sha_short }}
          platforms: linux/amd64
          push: true
